### ISSUE TITLE
[Bug] 0.38.8 画框选择区域的时候，图片模式不能生成图片了

### ISSUE THREAD

**Issue by qiekqiek** [RyotaUshio/obsidian-pdf-plus#114]
### Steps to reproduce

画框选择区域的时候，图片模式不能生成图片了

### Expected behavior

本来应该生成图片，插入笔记文档中

### Actual behavior

实际上插入了链接，但没有生成图片

### Screen recordings or screenshots (sandbox vault)

没有

### Obsidian debug info

没有

### PDF++ debug info

```json
没有
```

### Error messages

没有报错

**Comment by RyotaUshio** [comment]
I only understand Japanese and English so please write bug reports in either of these languages (preferably in English so that more people can understand it) using some auto-translation tool.
Also, the information you provided is so limited that it is nearly impossible to address your issue. Please do not intentionally ignore the bug report template.
I'm closing this issue but feel free to recreate a new issue following the above instructions. Thanks!
