### ISSUE TITLE
Something is wrong in the latest release

### ISSUE THREAD

**Issue by jcesguerram** [RyotaUshio/obsidian-pdf-plus#171]
### Steps to reproduce

I tried to add a highlight directly to the file. 
When I choose 'add highlight to file' with callout (or ahy other option i get a message saying 'an error ocurred while attepting to add an annotation'

### Expected behavior

I expected a highlight to be creates

### Actual behavior

a message appeared

### Screen recordings or screenshots (sandbox vault)

![Sin título](https://github.com/RyotaUshio/obsidian-pdf-plus/assets/122333212/468f8e4f-8db2-455b-806d-23d8370011d3)

### Obsidian debug info

-

### PDF++ debug info

```json
-
```

**Comment by RyotaUshio** [comment]
@jcesguerram Thanks, I have a few questions:
- Does the problem disappear when you install the previous versions of PDF++?
  - Manual installation: Go to the [releases](https://github.com/RyotaUshio/obsidian-pdf-plus/releases) page, download `main.js`, `styles.css` and `manifest.json` from the "Assets" section of the release to install, put these files under `.obsidian/plugins/pdf-plus` and replace old files with the same names, and reload Obsidian.
  - BRAT: Use the "with frozen version" feature.
- Does the problem happen to all PDF files, or only to a specific PDF?
- If it happens to only specific PDFs, can you share the files so that I can reproduce the problem?

**Comment by jcesguerram** [comment]
Oh this is embarrasing. I didn't try it with other pdfs before, and havign donde so I see that the problem is with this specific pdf. 
Here's the file (the highlights that are there were added with Acrobat Reader, which did work)
[Fiscal sustainability of health systems.pdf](https://github.com/RyotaUshio/obsidian-pdf-plus/files/15085460/Fiscal.sustainability.of.health.systems.pdf)

**Comment by RyotaUshio** [comment]
Thanks! Unfortunately, I couldn't reproduce it in my environment. I need **all** the requested information to figure out what's gone wrong in your case.

https://github.com/RyotaUshio/obsidian-pdf-plus/assets/72342591/5bb4b582-7d3e-4059-91b0-dbc5e039c7b5

**Comment by jcesguerram** [comment]
what's the 'debug info'? how can i share it?

**Comment by RyotaUshio** [comment]
It's explained in the bug report template:

<img width="878" alt="image" src="https://github.com/RyotaUshio/obsidian-pdf-plus/assets/72342591/03e20070-de7d-498b-97e6-166c33d8496f">

(You don't need to resubmit a new issue)

**Comment by jcesguerram** [comment]
thanks.
i don't know if it was beacause of the latest update (yesterday or today, i'm not sure) but it's fixed now

**Comment by RyotaUshio** [comment]
Great!

Next time please follow the template, it really helps to understand the situation. Thanks!
