### ISSUE TITLE
[FR] Frontmatter for use with supercharged links

### ISSUE THREAD

**Issue by r-curry** [RyotaUshio/obsidian-pdf-plus#189]
### Describe your request

Apologies if this is somehow already possible (have looked and it doesn't seem to be). 
It seems like it would be very useful if we could somehow included YAML/Frontmatter for pdfs saved in Obsidian, for use with the supercharged links plugin.

**Comment by RyotaUshio** [comment]
PDF files cannot contain YAML front matter due to the file format specification.
A possible workaround is to associate a markdown file with each PDF file and add front matter to that markdown file, for example, using the `PDF` property (which is specified here: obsidian://pdf-plus?setting=proxyMDProperty)

However, I guess Supercharged Links does not support this kind of stuff. I think this should be a feature request to that plugin rather than PDF++.
