### ISSUE TITLE
[FR] Adding pane options for how pdfs open

### ISSUE THREAD

**Issue by zuluwi** [RyotaUshio/obsidian-pdf-plus#3]
Can you add pane options to open pdfs as in "How to open markdown file" setting?

**Comment by RyotaUshio** [comment]
The "how to markdown file" setting was necessary because we can't specify how to open a link when doing it by `hover`+`cmd`, so I think the situation is different for opening normal PDF links.

Any reasons you don't want to use modifier keys (https://help.obsidian.md/User+interface/Use+tabs+in+Obsidian#Open+a+link)?
