### ISSUE TITLE
[FR] annotation popup  may not be displayed completely

### ISSUE THREAD

**Issue by niceczj** [RyotaUshio/obsidian-pdf-plus#320]
> SYSTEM INFO:
> OS: MacOS 15.1.1
> Obsidian version: 1.7.7
> PDF++ version:0.40.17

I’m a new user of Obsidian, and I accidentally discovered this amazing plugin called PDF++. This plugin is really great!

However, during my use, I found an area that could be improved. 
As shown in the image, if you add a annotation near the edge of the PDF and hover the mouse over it, the annotation popup may have part of its content hidden by the window edge.

Of course, it's also possible that I'm using it incorrectly.

![CleanShot 2024-12-24 at 05 09 46@2x 2](https://github.com/user-attachments/assets/6db38082-6082-40dd-866b-f9fb03c89101)

**Comment by RyotaUshio** [comment]
Thanks!
The annotation popup is in fact Obsidian's feature, and the positioning issue is Obsidian's bug rather than PDF++'s. So it has to be fixed by the Obsidian team.

You can find the bug report for this here:
https://forum.obsidian.md/t/pdf-viewer-annotation-note-pop-up-partially-hidden/67141

By the way, good luck on your Japanese learning! がんばってください
