### ISSUE TITLE
[FR] open pdf in obsidian from zotero

### ISSUE THREAD

**Issue by SSmJaE** [RyotaUshio/obsidian-pdf-plus#38]
if we directly set obsidian as the default app for PDF, when we open the PDF, we will redirected to the vault select panel in fact, 

I found a way to use the URI scheme, but this needs extra setup

I create a Python file and packaged it as a .exe file, which simply transfers the `open/start`  CLI command trigger by Zotero, to an obsidian open file scheme

```python
file_path = sys.argv[1]

# url encode
url_file_path = urllib.parse.quote(file_path)

# open by URL scheme
os.system(f"start obsidian://open?path={url_file_path}")
```

I just wonder if there is any better method to accomplish this behavior, since now with this plugin, we could use obsidian as the viewer and annotator, but we still need the capability Zotero provided to manage literature.

**Comment by RyotaUshio** [comment]
Thanks for sharing your interesting approach!

Just to confirm, do you put your Zotero PDFs (or symbolic links to them) inside your Obsidian vault? (Otherwise, I think PDF++ cannot help.)

I'm not sure I can answer this question properly because in my use case, I rarely open PDFs from Zotero.

After importing a paper to Zotero, I immediately import it into Obsidian using the Zotero Integration plugin.
[My template](https://github.com/RyotaUshio/obsidian-pdf-plus/files/14168966/Zotero.Integration.md) contains almost all metadata stored in Zotero, so I can query from the literature using Dataview, and I don't have back to Zotero except when updating the metadata.

I put a symbolic link to my Zotero folder, and my template contains an Obsidian link to the paper PDF in the Zotero folder as the `PDF` property. So I can open the PDF easily from within Obsidian.

**Comment by RyotaUshio** [comment]
I might want to send a feature request to [ZotLit](https://zotlit.aidenlx.top/).
ZotLit is composed of two components: an Obsidian plugin and a Zotero addon.
So the developer might be able to add the ability to open a PDF stored in the Obsidian vault from within Zotero to their Zotero addon.

**Comment by SSmJaE** [comment]
> (Just to confirm, do you put your Zotero PDFs (or symbolic links to them) inside your Obsidian vault? Otherwise, I think PDF++ cannot help.)

Yes, I use Zotfile to move the PDFs under the vault, while the whole folder is synced by OneDrive.
At the moment, this approach is a bit tricky, as I haven't yet managed to get Zotfile to move the PDFs automatically after import.🤷

> After importing a paper to Zotero, I immediately import it into Obsidian using the Zotero Integration plugin.

this is a considerable workflow, i should try this recently

> You might want to send a feature request to [ZotLit](https://zotlit.aidenlx.top/).

i will🫡

> This will open the literature note in your Obsidian vault. If you have a link to the PDF in the literature note, you can click it to open the PDF

this a good idea, but actually, these are two workflow

- One is what you mention here, opening the PDF via a link that points to the PDF file directly in the Obsidian note. This implicitly suggests that you use Obsidian to browse(choose, or any other proper word😏) the literature.
- Another is what I mentioned earlier, browsing the literature in Zotero, then opening it in Zotero, then automatically jumping to Obsidian.

the main difference is how you browse the literatures

currently i use zotero to browse, but i just realized that if i combine your method with canvas, i can somehow emulate the mind map view, which is much better than zotero's plain list view.

**Comment by RyotaUshio** [comment]
> One is what you mention here, opening the PDF via a link that points to the PDF file directly in the Obsidian note. This implicitly suggests that you use Obsidian to browse(choose, or any other proper word😏) the literature.

Not quite. You can primarily use Zotero to browse literature, and then right-click the item that you want to open in Obsidian.
The ZotLit addon for Zotero will then take you to the literature note in Obsidian.

I'm afraid there is not much I can do regarding this issue so I'm closing this.

**Comment by rauchert** [comment]
@SSmJaE 

Could you maybe give me a hint how to use your python code on macOS to open pdfs in Obsidian from inside Zotero? That would be fantastic. The pdfs that are associated with my Zotero entries are already stored in my Obsidian vault.

**Comment by SSmJaE** [comment]
@rauchert 

Apologies for the late response.

## Create an Executable File

To get started, you'll need to convert your Python script into an executable file. PyInstaller is a great tool for this, and it works across multiple platforms including Windows and macOS.

### Steps:

1. **Ensure you have Python installed on your system.**
2. **Install PyInstaller** by running `pip install pyinstaller` in your command prompt (Windows) or terminal (macOS).
3. **Compile your Python script into an executable file:**
   - For Windows: Run `pyinstaller --onefile your_script.py` in the command prompt.
   - For macOS: Run `pyinstaller --onefile your_script.py` in the terminal.
   This will create a single executable file (.exe on Windows and .app on macOS).

## Configure Zotero

1. Open Zotero and go to **Edit > Preferences**.
2. Navigate to the **General** tab.
3. Under **File Handling**, select **Use PDFs with** and then choose **Custom**.
4. Browse for and select the executable file that you created in the first step:
   - On Windows, choose the .exe file.
   - On macOS, choose the .app bundle.

**Note:** I'm not very familiar with macOS, but theoretically, the above steps should work. However, on macOS, adding a custom executable file might require some additional steps beyond what is described here.

After configuring Zotero, when you double-click on an item in Zotero or right-click to open the file, Zotero will launch the executable you've configured. You may notice that a terminal window briefly appears (it flashes on the screen and then disappears) before the file opens in Obsidian.

**Comment by rauchert** [comment]
@SSmJaE thanks a lot for you answer!

Basically, everything seems to work, except this: 
After having chosen my created .app bundle as the standard app for opening pdfs with Zotero and trying to open a pdf, nothing happens and the reason is this: 

sys.argv[1], which should be the filepath of the file to open, does not exist.
If I log sys.argv I can see that it contains only one element, namely the path of the app.

 Do you have any idea how to fix this and get the required filepath?
